### ISSUE TITLE
Figure out CSS development

### ISSUE THREAD

**Issue by cx1111** [cx1111/full-react-integration#3]
How can we set up CSS development?
- Material UI should work as the base style
- Individual/reusable components can override
- Some intelligent layout system
- Light/Dark Mode
- User Themes
- bug? Sometimes refreshing the page would lead to possibly conflicting styles between Material and X

**Comment by ahjota** [comment]
> bug? Sometimes refreshing the page would lead to possibly conflicting styles between Material and X
I've noticed this and I think it's actually related to being in development mode; the generated CSS styles line up on first load, but the server doesn't cleanly replace old styles with new ones, so things start to get out of whack. Restarting the dev server resolves these issues. None of this happens in production mode.
